version: "3.8"
name: assistant-app

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assistant
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./assistant-app/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/assistant.sql
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  keycloak-postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5234:5432"

  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8004:8080"
    depends_on:
      - keycloak-postgres

volumes:
  pg-data:
  minio-data: