version: "3.8"
name: assistant-app

services:
  gateway:
    container_name: "gateway"
    build:
      context: ./assistant-app-gateway/
      dockerfile: ./Dockerfile
    #image: assistant-app:gateway
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      MAIN_URL: http://host.docker.internal:8000/main-app/api-docs
      FM_URL: http://host.docker.internal:8000/file-manager/api-docs
    ports:
      - "8000:8000"
    volumes:
      - "ass-logs:/logs"
    depends_on:
      - "main"
      - "file-manager"

  main:
    container_name: "main"
    build:
      context: ./assistant-app/
      dockerfile: ./Dockerfile
    #image: assistant-app:main
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5434/assistant
      spring.liquibase.url: jdbc:postgresql://host.docker.internal:5434/assistant
    ports:
      - "8001:8001"
    volumes:
      - "ass-logs:/logs"

  file-manager:
    container_name: "file-manager"
    build:
      context: ./assistant-app-file-manager/
      dockerfile: ./Dockerfile
    #image: assistant-app:file-manager
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      file-manager.s3.url: http://host.docker.internal:9000
    ports:
      - "8002:8002"
    volumes:
      - "ass-logs:/logs"

volumes:
  ass-logs: