server:
  port: 8002

logging:
  file:
    path: logs/file-manager
  level:
    web: trace
    root: info

spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file-manager:
  s3:
    url: "http://127.0.0.1:9000"
    credentials:
      user: minioadmin
      password: minioadmin

springdoc:
  api-docs:
    path: /file-manager/api-docs
  swagger-ui:
    operationsSorter: method
    path: /file-manager/swagger-ui