server:
  port: 8001

logging:
  file:
    path: logs/app
  level:
    web: trace
    root: info
    org.hibernate.SQL: debug
    org.jooq.tools.LoggerListener: DEBUG

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: assistant-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/assistant
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1;
      idle-timeout: 30000
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/assistant

springdoc:
  api-docs:
    path: /main-app/api-docs
  swagger-ui:
    operationsSorter: method
    path: /main-app/swagger-ui